version: "3"

services: 
  web: 
    container_name: titanic-back
    restart: always
    build: .
    ports:
      - "4000:4000"
    links: 
      - mongo
    volumes:
      - .:/usr/src/app
  mongo: 
    container_name: mongo_db
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=titanic
    ports: 
      - "27017:27017"